# -*- coding: utf-8 -*-
"""diabetes_eda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUyYFEByeSYmohiN079IALYBD0bzP1i-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("diabetes (1).csv")

df.shape
df.info()
df.describe()

df.isnull().sum()

cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

df[cols] = df[cols].replace(0, np.nan)

df.isnull().sum()

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.show()

df.hist(figsize=(12,10), bins=20)
plt.show()

plt.figure(figsize=(12,8))

sns.histplot(df["Glucose"], kde=True)
plt.title("Glucose Distribution")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# df already loaded

cols = ["Pregnancies","Glucose","BloodPressure","SkinThickness",
        "Insulin","BMI","DiabetesPedigreeFunction","Age"]

plt.figure(figsize=(14,10))

for i, col in enumerate(cols):
    plt.subplot(3,3,i+1)
    sns.kdeplot(df[col], fill=True)
    plt.title(f"{col} Distribution Curve")

plt.tight_layout()
plt.show()

cols = ["Pregnancies","Glucose","BloodPressure","SkinThickness",
        "Insulin","BMI","DiabetesPedigreeFunction","Age"]

plt.figure(figsize=(14,12))

for i, col in enumerate(cols):
    plt.subplot(3,3,i+1)
    sns.kdeplot(data=df, x=col, hue="Outcome", fill=True)
    plt.title(col)

plt.tight_layout()
plt.show()

corr = df.corr()
print(corr)

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

print(corr["Outcome"].sort_values(ascending=False))

sns.pairplot(df, hue="Outcome")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(data=df, x="Glucose", y="BMI", hue="Outcome")
plt.title("Glucose vs BMI (Outcome wise)")
plt.show()
sns.scatterplot(data=df, x="Age", y="Glucose", hue="Outcome")
plt.title("Age vs Glucose Scatter Plot")
plt.show()
sns.scatterplot(data=df, x="Age", y="BMI", hue="Outcome")
plt.title("Age vs BMI Scatter Plot")
plt.show()
sns.scatterplot(data=df, x="Insulin", y="Glucose", hue="Outcome")
plt.title("Insulin vs Glucose Scatter Plot")
plt.show()
sns.pairplot(df, hue="Outcome")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(14,10))

for i, col in enumerate(df.columns[:-1]):
    plt.subplot(3,3,i+1)
    sns.boxplot(y=df[col])
    plt.title(col)

plt.tight_layout()
plt.show()

df_clean = df.drop(columns=["SkinThickness", "Insulin"])
print(df_clean.shape)
print(df_clean.head())
import seaborn as sns
import matplotlib.pyplot as plt

corr = df_clean.corr()

plt.figure(figsize=(8,5))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation After Removing Bad Features")
plt.show()
features = ["Pregnancies","Glucose","BloodPressure","BMI","DiabetesPedigreeFunction","Age"]

X = df_clean[features]
y = df_clean["Outcome"]

print(X.head())
print(y.head())