# -*- coding: utf-8 -*-
"""EcoVolt Smart Load Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aZn7waoh_seRyI1YA_7Irn7YzdBmD2w
"""

!pip install streamlit -q
!pip install pyngrok -q
!npm install -g localtunnel -q
!pip install plotly -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pickle
# import plotly.express as px
# import plotly.graph_objects as go
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.model_selection import train_test_split
# 
# # --- Page Config ---
# st.set_page_config(page_title="EcoVolt AI Dashboard", layout="wide")
# 
# # --- 1. Data Generation / Loading ---
# @st.cache_data
# def load_data():
#     # এখানে ডামি ডেটা তৈরি করা হচ্ছে, আপনি চাইলে pd.read_csv("eco_volt_30days.csv") দিতে পারেন
#     np.random.seed(42)
#     rows = 500
#     data = {
#         'hour': np.random.randint(0, 24, rows),
#         'day': np.random.randint(1, 31, rows),
#         'month': np.random.randint(1, 13, rows),
#         'temperature': np.random.randint(15, 45, rows),
#         'humidity': np.random.randint(30, 90, rows),
#         'prev_load': np.random.randint(100, 800, rows),
#         'weekend': np.random.randint(0, 2, rows),
#         'load': np.random.randint(150, 850, rows)
#     }
#     return pd.DataFrame(data)
# 
# df = load_data()
# 
# # --- 2. Model Training ---
# X = df[['hour', 'day', 'month', 'temperature', 'humidity', 'prev_load', 'weekend']]
# y = df['load']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 
# model = RandomForestRegressor(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)
# 
# # --- 3. Streamlit UI ---
# st.title("⚡ EcoVolt Smart Load Analytics")
# st.markdown("Machine Learning ভিত্তিক বিদ্যুৎ সাশ্রয় এবং লোড পূর্বাভাস সিস্টেম।")
# 
# # Sidebar inputs
# st.sidebar.header("📥 Input Features")
# h = st.sidebar.slider("Hour of Day", 0, 23, 12)
# t = st.sidebar.slider("Temperature (°C)", 10, 50, 30)
# hum = st.sidebar.slider("Humidity (%)", 10, 100, 60)
# p_load = st.sidebar.number_input("Previous Load (W)", 0, 1000, 300)
# w_end = st.sidebar.selectbox("Weekend?", [0, 1], format_func=lambda x: "Yes" if x==1 else "No")
# 
# # Prediction Logic
# input_data = np.array([[h, 15, 5, t, hum, p_load, w_end]])
# prediction = model.predict(input_data)[0]
# 
# # --- Layout: Charts and Metrics ---
# col1, col2 = st.columns([1, 2])
# 
# with col1:
#     st.subheader("🔮 Prediction Result")
#     st.metric(label="Predicted Load", value=f"{prediction:.2f} Watts", delta=f"{prediction - p_load:.2f} vs Prev")
# 
#     # Gauge Chart
#     fig_gauge = go.Figure(go.Indicator(
#         mode = "gauge+number",
#         value = prediction,
#         title = {'text': "Load Intensity"},
#         gauge = {'axis': {'range': [None, 1000]},
#                  'bar': {'color': "darkblue"},
#                  'steps' : [
#                      {'range': [0, 400], 'color': "lightgreen"},
#                      {'range': [400, 700], 'color': "yellow"},
#                      {'range': [700, 1000], 'color': "red"}]}
#     ))
#     st.plotly_chart(fig_gauge, use_container_width=True)
# 
# with col2:
#     st.subheader("📊 Data Trends & Correlations")
#     tab1, tab2 = st.tabs(["Load Trend", "Temp vs Load"])
# 
#     with tab1:
#         # সময়ের সাথে লোডের গ্রাফ
#         fig_line = px.line(df.head(50), y='load', title="Recent Load Patterns", template="plotly_dark")
#         st.plotly_chart(fig_line, use_container_width=True)
# 
#     with tab2:
#         # টেম্পারেচার এর সাথে লোডের সম্পর্ক
#         fig_scatter = px.scatter(df, x='temperature', y='load', color='humidity',
#                                  title="Temperature vs Load Correlation")
#         st.plotly_chart(fig_scatter, use_container_width=True)
# 
# st.divider()
# if st.checkbox("View Raw Dataset"):
#     st.dataframe(df.style.highlight_max(axis=0))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pickle
# import plotly.express as px
# 
# # এরর এড়াতে এই কনফিগারেশন যোগ করা হয়েছে
# st.set_page_config(page_title="EcoVolt AI", layout="wide")
# 
# # এটি ব্রাউজারের ডাইনামিক রেন্ডারিং সমস্যা কমাবে
# st.markdown("""
#     <style>
#     .reportview-container {
#         background: #0e1117;
#     }
#     </style>
#     """, unsafe_allow_html=True)
# 
# # বাকি সব আগের মতো থাকবে...
# # (আপনার আগের মডেল লোডিং এবং UI কোড এখানে থাকবে)

# ১. আইপি এড্রেস কপি করে রাখুন
print("আপনার Endpoint IP টি হলো:")
!curl ipv4.icanhazip.com

# ২. সার্ভার রান করুন
!streamlit run app.py & npx localtunnel --port 8501