# -*- coding: utf-8 -*-
"""EcoVolt Smart Load Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aZn7waoh_seRyI1YA_7Irn7YzdBmD2w
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# --- পেজ কনফিগারেশন ---
st.set_page_config(page_title="EcoVolt Smart Dashboard", layout="wide")

# --- ১. ডেটা প্রস্তুতি (সরাসরি কোডেই জেনারেট করা হচ্ছে) ---
@st.cache_data
def load_data():
    np.random.seed(42)
    rows = 1000
    data = {
        'hour': np.random.randint(0, 24, rows),
        'day': np.random.randint(1, 31, rows),
        'month': np.random.randint(1, 13, rows),
        'temperature': np.random.randint(15, 45, rows),
        'humidity': np.random.randint(30, 90, rows),
        'prev_load': np.random.randint(100, 800, rows),
        'weekend': np.random.randint(0, 2, rows),
        'load': np.random.randint(150, 850, rows)
    }
    return pd.DataFrame(data)

df = load_data()

# --- ২. মডেল ট্রেনিং ---
@st.cache_resource
def train_model(data):
    X = data[['hour', 'day', 'month', 'temperature', 'humidity', 'prev_load', 'weekend']]
    y = data['load']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    return model

model = train_model(df)

# --- ৩. ইউজার ইন্টারফেস (UI) ---
st.title("⚡ EcoVolt Smart Load Analytics")
st.markdown("Machine Learning ভিত্তিক স্মার্ট এনার্জি ম্যানেজমেন্ট সিস্টেম।")

# সাইডবার ইনপুট
st.sidebar.header("📥 ইনপুট ফিচারসমূহ")
h = st.sidebar.slider("দিনের সময় (Hour)", 0, 23, 12)
t = st.sidebar.slider("তাপমাত্রা (°C)", 10, 50, 30)
hum = st.sidebar.slider("আর্দ্রতা (%)", 10, 100, 60)
p_load = st.sidebar.number_input("পূর্ববর্তী লোড (Watts)", 0, 1000, 300)
w_end = st.sidebar.selectbox("ছুটির দিন কি না?", [0, 1], format_func=lambda x: "হ্যাঁ" if x==1 else "না")

# প্রেডিকশন লজিক (DataFrame ব্যবহার করা হয়েছে এরর এড়াতে)
input_cols = ['hour', 'day', 'month', 'temperature', 'humidity', 'prev_load', 'weekend']
input_df = pd.DataFrame([[h, 15, 5, t, hum, p_load, w_end]], columns=input_cols)
prediction = model.predict(input_df)[0]

# --- ৪. লেআউট: চার্ট এবং মেট্রিক্স ---
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("🔮 পূর্বাভাসের ফলাফল")
    st.metric(label="সম্ভাব্য লোড (Predicted Load)",
              value=f"{prediction:.2f} Watts",
              delta=f"{prediction - p_load:.2f} vs Previous")

    # গেজ চার্ট (Gauge Chart)
    fig_gauge = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = prediction,
        gauge = {'axis': {'range': [None, 1000]},
                 'bar': {'color': "#1f77b4"},
                 'steps' : [
                     {'range': [0, 400], 'color': "#d1e7dd"},
                     {'range': [400, 700], 'color': "#fff3cd"},
                     {'range': [700, 1000], 'color': "#f8d7da"}]}
    ))
    st.plotly_chart(fig_gauge, width='stretch')

with col2:
    st.subheader("📊 লোড ট্রেন্ড এবং রিলেশন")
    tab1, tab2 = st.tabs(["ব্যবহারের ধরন", "তাপমাত্রা vs লোড"])

    with tab1:
        fig_line = px.line(df.head(100), y='load', title="সাম্প্রতিক লোড প্যাটার্ন", template="plotly_dark")
        st.plotly_chart(fig_line, width='stretch')

    with tab2:
        fig_scatter = px.scatter(df, x='temperature', y='load', color='humidity',
                                 title="তাপমাত্রার সাথে লোডের সম্পর্ক")
        st.plotly_chart(fig_scatter, width='stretch')

st.divider()