# -*- coding: utf-8 -*-
"""EcoVolt Smart Load Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aZn7waoh_seRyI1YA_7Irn7YzdBmD2w
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# --- 1. Page Configuration ---
st.set_page_config(page_title="EcoVolt Smart Dashboard", layout="wide")

# --- 2. Data Preparation ---
@st.cache_data
def load_data():
    np.random.seed(42)
    rows = 1000
    data = {
        'hour': np.random.randint(0, 24, rows),
        'day': np.random.randint(1, 31, rows),
        'month': np.random.randint(1, 13, rows),
        'temperature': np.random.randint(15, 45, rows),
        'humidity': np.random.randint(30, 90, rows),
        'prev_load': np.random.randint(100, 800, rows),
        'weekend': np.random.randint(0, 2, rows),
        'load': np.random.randint(150, 850, rows)
    }
    return pd.DataFrame(data)

df = load_data()

# --- 3. Model Training ---
@st.cache_resource
def train_model(data):
    X = data[['hour', 'day', 'month', 'temperature', 'humidity', 'prev_load', 'weekend']]
    y = data['load']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    return model

model = train_model(df)

# --- 4. User Interface (UI) ---
st.title("EcoVolt Smart Load Analytics")
st.markdown("Machine Learning based Smart Energy Management System.")

# Sidebar for Inputs
st.sidebar.header("Input Features")
h = st.sidebar.slider("Hour of Day", 0, 23, 12)
t = st.sidebar.slider("Temperature (°C)", 10, 50, 30)
hum = st.sidebar.slider("Humidity (%)", 10, 100, 60)
p_load = st.sidebar.number_input("Previous Load (Watts)", 0, 1000, 300)
w_end = st.sidebar.selectbox("Is it a Weekend?", [0, 1], format_func=lambda x: "Yes" if x==1 else "No")

# Prediction Logic
input_cols = ['hour', 'day', 'month', 'temperature', 'humidity', 'prev_load', 'weekend']
input_df = pd.DataFrame([[h, 15, 5, t, hum, p_load, w_end]], columns=input_cols)
prediction = model.predict(input_df)[0]

# --- 5. Visualizations ---
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader(" Forecast Result")
    st.metric(label="Predicted Load", value=f"{prediction:.2f} Watts", delta=f"{prediction - p_load:.2f}")

    fig_gauge = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = prediction,
        title = {'text': "Load Intensity"},
        gauge = {'axis': {'range': [None, 1000]},
                 'bar': {'color': "#1f77b4"},
                 'steps' : [
                     {'range': [0, 400], 'color': "#d1e7dd"},
                     {'range': [400, 700], 'color': "#fff3cd"},
                     {'range': [700, 1000], 'color': "#f8d7da"}]}
    ))
    st.plotly_chart(fig_gauge, use_container_width=True)

with col2:
    st.subheader("Data Trends")
    tab1, tab2 = st.tabs(["Load Trend", "Temp vs Load"])
    with tab1:
        fig_line = px.line(df.head(100), y='load', title="Recent Load Patterns", template="plotly_dark")
        st.plotly_chart(fig_line, use_container_width=True)
    with tab2:
        fig_scatter = px.scatter(df, x='temperature', y='load', color='humidity', title="Temp vs Load Correlation")
        st.plotly_chart(fig_scatter, use_container_width=True)

# --- 6. Raw Data ---
st.divider()
if st.checkbox("Show Raw Dataset"):
    st.dataframe(df, use_container_width=True)

st.info("Tip: Use the sidebar to update predictions in real-time.")