# -*- coding: utf-8 -*-
"""house_price_eda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1DfPubxltI2nxa3M3kZpA4oyDDct0U9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Housing (1).csv")

df.shape
df.info()
df.describe()

df.isnull().sum()

plt.figure(figsize=(8,5))
sns.histplot(df['price'], kde=True)
plt.title("House Price Distribution")
plt.show()

num_cols = df.select_dtypes(include=['int64','float64']).columns

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

features = ['area','bedrooms','bathrooms','stories','parking']

for col in features:
    plt.figure(figsize=(6,4))
    sns.scatterplot(x=df[col], y=df['price'])
    plt.title(f"Price vs {col}")
    plt.show()

cat_cols = ['mainroad','guestroom','basement','hotwaterheating',
            'airconditioning','prefarea','furnishingstatus']

for col in cat_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col], y=df['price'])
    plt.title(f"Price vs {col}")
    plt.show()

def detect_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[col] < lower) | (df[col] > upper)]

detect_outliers(df, 'price')